# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://arslan_moosa_db_7_2_part5_user:kt1elXjAhkVGHlfQkxELlT8EcXJAGmXJ@dpg-crnulv08fa8c738l3fug-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part5
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://arslan_moosa_db_7_2_part5_user:kt1elXjAhkVGHlfQkxELlT8EcXJAGmXJ@dpg-crnulv08fa8c738l3fug-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part5
    restart: "no"