# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://arslan_moosa_db_7_2_part4_user:W6kze7sSHnLOe4lyZgw0z2VAPJG1rynd@dpg-crmtmr56l47c73fu9i6g-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part4
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://arslan_moosa_db_7_2_part4_user:W6kze7sSHnLOe4lyZgw0z2VAPJG1rynd@dpg-crmtmr56l47c73fu9i6g-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part4
    restart: "no"