
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: ampart5.azurecr.io/book-catalog-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        env:
        - name: PORT
          value: "8088"
        - name: DATABASE_URL
          value: "postgresql://arslan_moosa_db_7_2_part5_user:kt1elXjAhkVGHlfQkxELlT8EcXJAGmXJ@dpg-crnulv08fa8c738l3fug-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part5"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: ampart5.azurecr.io/inventory-management-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        env:
        - name: PORT
          value: "8089"
        - name: DATABASE_URL
          value: "postgresql://arslan_moosa_db_7_2_part5_user:kt1elXjAhkVGHlfQkxELlT8EcXJAGmXJ@dpg-crnulv08fa8c738l3fug-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part5"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089